### ISSUE TITLE
Support for Astro v2 betas

### ISSUE THREAD

**Issue by ankushg** [astro-community/astro-embed#35]
I'm getting peer conflicts when building using Astro v2.0.0-beta.3 due to the ^1.0.0 peer dependency.

When I use `--force` though, the embeds seem to work!

**Comment by delucis** [comment]
Ah yes, we’ll need to update the peer dependency ranges. Would you be up for submitting a PR? A range of `^1.0.0 || ^2.0.0-beta` should do the trick.

**Comment by delucis** [comment]
Fixed in the latest release — thanks @ankushg 🙌
