### ISSUE TITLE
Unknown file extension ".astro" for /home/dev/astro/node_modules/@astro-community/astro-embed-youtube/YouTube.astro

### ISSUE THREAD

**Issue by ngmisl** [astro-community/astro-embed#41]
I can't seem to make this work

**Comment by delucis** [comment]
Hi @ngmisl! Please provide some information about your project set-up, code used, etc. to help debug.

**Comment by delucis** [comment]
Closing for lack of detail. Please feel free to post if you can share more, thank you!

**Comment by Zygar** [comment]
Same issue here

Unknown file extension ".astro" for /Users/andy/Projects/varda-web/node_modules/@astro-community/astro-embed-vimeo/Vimeo.astro

You likely need to add this package to vite.ssr.noExternal in your astro config file.


Astro 2.6; local dev server

import { Vimeo } from "@astro-community/astro-embed-vimeo";
<Vimeo id="https://vimeo.com/32001208" />
